dist: xenial
sudo: required
language: go

go:
  - 1.13.x

cache:
  directories:
    - $GOPATH/pkg/mod

git:
  depth: 1

install:
  - make tools

script:
  - make lint
  - make test

branches:
  only:
    - master
    - /^v.*$/

deploy:
  - provider: script
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_OS_NAME = linux
