dist: xenial
sudo: required
services:
  - docker
language: go

cache:
  directories:
    - $GOPATH/pkg/mod

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - go: "1.14.x"
      name: "Code Lint"
      script: make lint
    - go: "1.14.x"
      name: "Code UnitTest"
      script: make test
    - go: "1.14.x"
      name: "Dependencies"
      script: make depscheck
    - go: "1.14.x"
      name: "Website"
      script:
        - make docscheck
        # - make website-test
        - make website-lint

install:
  - make tools

branches:
  only:
    - master
    - /^v.*$/

deploy:
  - provider: script
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_OS_NAME = linux
